/** @type {import('tailwindcss').Config} */
// Theme tokens ported verbatim from the Stitch "WorldCup Live" design system.
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#ffe08f",
        "surface-container-lowest": "#0a0d1e",
        "surface-tint": "#eec13c",
        "on-primary-fixed-variant": "#584400",
        "tertiary-container": "#ffbdbb",
        "secondary-fixed-dim": "#62de8e",
        "on-surface": "#dfe1fa",
        "surface-container-highest": "#303447",
        "secondary-fixed": "#7ffba8",
        "tertiary-fixed": "#ffdad8",
        "on-secondary-fixed-variant": "#005229",
        "error-container": "#93000a",
        "inverse-surface": "#dfe1fa",
        "surface-dim": "#0f1224",
        "surface-container-high": "#26293b",
        secondary: "#15a35a",
        background: "#0f1224",
        error: "#ffb4ab",
        "on-secondary-container": "#ffffff",
        surface: "#0f1224",
        "outline-variant": "#4e4634",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#b10025",
        "on-error": "#690005",
        "on-tertiary-fixed": "#410007",
        "on-tertiary": "#680011",
        "primary-fixed-dim": "#eec13c",
        "on-primary-container": "#6c5400",
        tertiary: "#ffe3e2",
        "on-error-container": "#ffdad6",
        "surface-bright": "#35384b",
        "tertiary-fixed-dim": "#ffb3b1",
        "on-primary": "#3d2e00",
        "on-background": "#dfe1fa",
        "secondary-container": "#15a35a",
        "surface-container": "#1b1f30",
        primary: "#ffe7af",
        "surface-variant": "#303447",
        "on-surface-variant": "#d1c5ae",
        "on-secondary-fixed": "#00210d",
        "on-tertiary-fixed-variant": "#92001d",
        outline: "#9a907b",
        "inverse-on-surface": "#2c2f42",
        "on-primary-fixed": "#241a00",
        "inverse-primary": "#755b00",
        "primary-container": "#f5c842",
        "surface-container-low": "#171a2c",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "12px",
        "margin-edge": "32px",
        xl: "80px",
        base: "8px",
        md: "24px",
        xs: "4px",
        lg: "48px",
        gutter: "24px",
      },
      fontFamily: {
        "title-md": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Bebas Neue", "sans-serif"],
        "headline-lg-mobile": ["Bebas Neue", "sans-serif"],
        "display-lg": ["Bebas Neue", "sans-serif"],
        "display-sm": ["Bebas Neue", "sans-serif"],
      },
      fontSize: {
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "36px", letterSpacing: "0.03em", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "32px", fontWeight: "400" }],
        "display-lg": ["80px", { lineHeight: "80px", letterSpacing: "0.02em", fontWeight: "400" }],
        "display-sm": ["56px", { lineHeight: "56px", letterSpacing: "0.02em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
